//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleVendor.Reports {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ReportSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ReportSettings defaultInstance = ((ReportSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ReportSettings())));
        
        public static ReportSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=..\\..\\Report.xlsx;Extended Properti" +
            "es=\"Excel 12.0 Xml;HDR=YES\";")]
        public string OleDbConnectionString {
            get {
                return ((string)(this["OleDbConnectionString"]));
            }
            set {
                this["OleDbConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=..\\..\\..\\SQLiteDatabase\\nissan_costs.sqlite;Version=3;")]
        public string SQLiteConnectionString {
            get {
                return ((string)(this["SQLiteConnectionString"]));
            }
            set {
                this["SQLiteConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../Reports/PdfReport.pdf")]
        public string PDFFileName {
            get {
                return ((string)(this["PDFFileName"]));
            }
            set {
                this["PDFFileName"] = value;
            }
        }
    }
}
